# Generated by Django 5.1.1 on 2024-09-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyectos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=200)),
                ("Descripcion", models.CharField(max_length=200)),
                ("Imagen", models.CharField(max_length=200)),
                ("Video_url", models.CharField(max_length=200)),
            ],
        ),
    ]
