# Generated by Django 5.1.1 on 2024-09-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=200)),
                ("Decripcion", models.CharField(max_length=200)),
                ("Imagen", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Servicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=200)),
                ("Decripcion", models.CharField(max_length=200)),
                ("Imagen", models.CharField(max_length=200)),
            ],
        ),
    ]
